# CI for NVIP

name: Java CI

on: [push]

env:
  AWS_REGION: 'us-east-1'
  S3_BUCKET_NAME_UI: 'www.cve.live'
  ANGULAR_CLI_VERSION: '15.1.0'

jobs:
  build-test-crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Prepare MySQL Test DB
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE nvip;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
          mysql -e 'source nvip_data/mysql-database/CreateAndInitializeDb.sql' -uroot -proot

      - name: Test and Build Backend with Maven
        run: |
          mvn install:install-file \
            -Dfile=sleepycat-5.0.84.jar \
            -DgroupId=com.sleepycat \
            -DartifactId=je \
            -Dversion=5.0.84 \
            -Dpackaging=jar \
            -DgeneratePom=true
          mvn dependency:go-offline
          mvn package -DskipTests

  deploy-crawler:
    runs-on: ubuntu-latest
    needs: build-test-crawler
    if: ${{ success() && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3

  package:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image for Backend
        run: |
          docker build . -t nvip-crawler:latest -t ghcr.io/softwaredesignlab/nvip-crawler:latest
          docker push ghcr.io/softwaredesignlab/nvip-crawler:latest
