# CI for NVIP

name: Java CI

on: [push]

env:
  AWS_REGION: 'us-east-1'

jobs:
  # Build Main Project
  build-test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Grab large files form S3 bucket
      - name: Pull file from S3 bucket
        run: |
          cd nvip_data/productnameextraction
          aws s3 cp s3://binaries-for-crawler/w2v_model_250.bin .

      # MySQL DB for tests that require connection
      - name: Prepare MySQL Test DB
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE nvip;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
          mysql -e 'source nvip_data/mysql-database/CreateAndInitializeDb.sql' -uroot -proot

      - name: Test and Build Backend with Maven
        run: |
          mvn dependency:go-offline
          mvn package

      # Test report for tests that fail/skip
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1

  # Build and test crawler component
  build-test-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Setup MySQL DB for tests that require connection (Might not need this)
      - name: Prepare MySQL Test DB
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE nvip;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
          mysql -e 'source nvip_data/mysql-database/CreateAndInitializeDb.sql' -uroot -proot

      - name: Test and Build Crawler with Maven
        run: |
          cd crawler
          mvn dependency:go-offline
          mvn package

      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1

  # Build and Test Reconciler Component
  build-test-reconciler:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Might not need this
      - name: Prepare MySQL Test DB
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE nvip;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
          mysql -e 'source nvip_data/mysql-database/CreateAndInitializeDb.sql' -uroot -proot

      - name: Test and Build Reconciler with Maven
        run: |
          cd reconciler
          mvn dependency:go-offline
          mvn package

      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1

  # Build and Test Product Extraction Component
  build-test-product-extractor:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Grab large files (w2v model) from S3 bucket
      - name: Pull file from S3 bucket
        run: |
          cd productnameextractor/nvip_data/productnameextraction
          aws s3 cp s3://binaries-for-crawler/w2v_model_250.bin .

      # Might not need this
      - name: Prepare MySQL Test DB
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE nvip;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
          mysql -e 'source nvip_data/mysql-database/CreateAndInitializeDb.sql' -uroot -proot

      - name: Test and Build Reconciler with Maven
        run: |
          cd productnameextractor
          mvn dependency:go-offline
          mvn package

      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1

  # Deploy main backend project to container registry
  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-test-backend
    if: ${{ success() && github.ref == 'refs/heads/dev' }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Pull large files so they're in the container
      - name: Pull file from S3 bucket
        run: |
          cd nvip_data/productnameextraction
          aws s3 cp s3://binaries-for-crawler/w2v_model_250.bin .  

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Main project is called nvip-crawler, crawler component will be nvip-crawler-sub
      - name: Build and Push Docker Image for Backend
        run: |
          docker build . -t nvip-crawler:dev -t ghcr.io/softwaredesignlab/nvip-crawler:dev
          docker push ghcr.io/softwaredesignlab/nvip-crawler:dev

  # Deploy crawler component project to container registry
  deploy-crawler:
    runs-on: ubuntu-latest
    needs: build-test-crawler
    if: ${{ success() && github.ref == 'refs/heads/dev' }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image for Backend
        run: |
          cd crawler
          docker build . -t nvip-crawler-sub:dev -t ghcr.io/softwaredesignlab/nvip-crawler-sub:dev
          docker push ghcr.io/softwaredesignlab/nvip-crawler-sub:dev     
  

  # Deploy reconciler component project to container registry
  deploy-reconciler:
    runs-on: ubuntu-latest
    needs: build-test-reconciler
    if: ${{ success() && github.ref == 'refs/heads/dev' }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image for Backend
        run: |
          cd reconciler
          docker build . -t nvip-reconciler:dev -t ghcr.io/softwaredesignlab/nvip-reconciler:dev
          docker push ghcr.io/softwaredesignlab/nvip-reconciler:dev  

  # Deploy product extractor project to container registry
  deploy-product-extractor:
    runs-on: ubuntu-latest
    needs: build-test-product-extractor
    if: ${{ success() && github.ref == 'refs/heads/dev' }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Pull large files (w2v model) so they're in the container
      - name: Pull file from S3 bucket
        run: |
          cd productnameextractor/nvip_data/productnameextraction
          aws s3 cp s3://binaries-for-crawler/w2v_model_250.bin . 

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image for Backend
        run: |
          cd productnameextractor
          docker build . -t nvip-product-extractor:dev -t ghcr.io/softwaredesignlab/nvip-product-extractor:dev
          docker push ghcr.io/softwaredesignlab/nvip-product-extractor:dev 
